const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('help')
        .setDescription('Lists all available commands or provides info about a specific command.')
        .addStringOption(option =>
            option.setName('command')
                .setDescription('The command to get info about')
                .setRequired(false)),
    async execute(interaction) {
        const { client } = interaction;
        const commandName = interaction.options.getString('command');

        if (commandName) {
            // Handle specific command help
            const command = client.commands.get(commandName.toLowerCase());

            if (!command) {
                return interaction.reply({
                    content: `我找不到名为 \`${commandName}\` 的命令。(I couldn't find a command named \`${commandName}\`.)`,
                    ephemeral: true
                });
            }

            const embed = new EmbedBuilder()
                .setColor('#0099ff')
                .setTitle(`/${command.data.name} Command Info`)
                .setDescription(command.data.description || '没有提供描述。(No description provided.)');

            // You can add more details here if your commands have more properties like options, usage, etc.
            if (command.data.options && command.data.options.length > 0) {
                const options = command.data.options.map(opt => {
                    let optString = `\`${opt.name}\`: ${opt.description}`;
                    if (opt.required) optString += ' (Required)';
                    return optString;
                }).join('\n');
                embed.addFields({ name: 'Options (选项)', value: options });
            }

            return interaction.reply({ embeds: [embed], ephemeral: true });

        } else {
            // List all commands
            const commands = client.commands.map(command => `\`/${command.data.name}\` - ${command.data.description || '没有描述。(No description.)'}`);

            const embed = new EmbedBuilder()
                .setColor('#0099ff')
                .setTitle('🤖 Available Commands (可用命令)')
                .setDescription(
                    `以下是我所有的命令：\n(Here are all my commands:)\n\n${commands.join('\n')}\n\n` +
                    `你可以使用 \`/help [命令名称]\` 来获取特定命令的更多信息。\n(You can use \`/help [command name]\` for more info on a specific command.)`
                )
                .setFooter({ text: '由 Gemini CLI 生成 (Generated by Gemini CLI)' })
                .setTimestamp();

            return interaction.reply({ embeds: [embed], ephemeral: true });
        }
    },
};